---
development:
  cloud_name: whoswhoplus
  api_key: '459282169329741'
  api_secret: ZRtsDxC9ZRX6JJXsk9E0SBEFgYc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: whoswhoplus
  api_key: '459282169329741'
  api_secret: ZRtsDxC9ZRX6JJXsk9E0SBEFgYc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: whoswhoplus
  api_key: '459282169329741'
  api_secret: ZRtsDxC9ZRX6JJXsk9E0SBEFgYc
  enhance_image_tag: true
  static_image_support: false
